Removed XZ compression feature of serialized IValues
usethesource/vallang pull request #253
Opened 2024-04-03 08:56 UTC by DavyLandman

Fixes #252

2024-04-03 10:02 UTC, jurgenvinju commented on src/main/java/io/usethesource/vallang/io/binary/stream/Compressor.java
> +                throw new IOException("XZ compression is not supported anymore, please use an older version of rascal/vallang to open the file and store it with a different level of compression");
same same

2024-04-03 10:03 UTC, jurgenvinju commented on src/main/java/io/usethesource/vallang/io/binary/stream/Header.java
> +        /** Not used anymore, it was never used, and we're cutting down on dependencies */
rename `XZ` to `USED_TO_BE_XZ` or something?

2024-04-03 10:05 UTC, jurgenvinju commented on src/main/java/io/usethesource/vallang/io/binary/stream/IValueInputStream.java
> +            throw new IOException("Incorrect file header, are you sure this is a valid file containing a serialized value?");
pedantic error message (a rhetorical question). "Unexpected file header: "; perhaps print the current header and the expected header inside the message?

2024-04-03 10:06 UTC, jurgenvinju requested changes
nice to get this over with!

2024-04-03 11:45 UTC, DavyLandman commented on src/main/java/io/usethesource/vallang/io/binary/stream/IValueOutputStream.java
> +        Extreme(Header.Compression.ZSTD, 19),
Well, the zstd compression modes are different than xz. and 19 is the highest for zstd that doesn't require special flags. and it's "close" to xz at 6.

2024-04-03 11:57 UTC, DavyLandman commented
@jurgenvinju thanks, done, squash & merge when approved :)

2024-04-09 08:06 UTC, jurgenvinju approved these changes

2024-04-09 08:06 UTC, jurgenvinju commented
Thanks!

2024-04-09 08:06 UTC, merged